/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import database.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author karpa
 */
public class Customer extends javax.swing.JFrame {

    private int cust_id = 0;

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private boolean validateFields() {
        if (!name.getText().equals("") && !phone.getText().equals("") && !addr.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ctable = new javax.swing.JTable();
        txtid = new javax.swing.JLabel();
        txtname = new javax.swing.JLabel();
        txtphone = new javax.swing.JLabel();
        txtaddr = new javax.swing.JLabel();
        custid = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        addr = new javax.swing.JTextField();
        btre = new javax.swing.JButton();
        bts = new javax.swing.JButton();
        btc = new javax.swing.JButton();
        btu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CUSTOMER ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 28, -1, -1));

        ctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Name", "Phone", "Address"
            }
        ));
        ctable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ctableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ctable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        txtid.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtid.setForeground(new java.awt.Color(255, 255, 255));
        txtid.setText("Customer ID");
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 230, -1, -1));

        txtname.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(255, 255, 255));
        txtname.setText("Name");
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 280, -1, -1));

        txtphone.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtphone.setForeground(new java.awt.Color(255, 255, 255));
        txtphone.setText("Phone");
        getContentPane().add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 330, -1, -1));

        txtaddr.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtaddr.setForeground(new java.awt.Color(255, 255, 255));
        txtaddr.setText("Address");
        getContentPane().add(txtaddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 380, -1, -1));
        getContentPane().add(custid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 230, 240, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 280, 240, -1));
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 330, 240, -1));
        getContentPane().add(addr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 380, 240, -1));

        btre.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btre.setText("RESET");
        btre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btreActionPerformed(evt);
            }
        });
        getContentPane().add(btre, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 450, -1, -1));

        bts.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        bts.setText("SAVE");
        bts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsActionPerformed(evt);
            }
        });
        getContentPane().add(bts, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 450, -1, -1));

        btc.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btc.setText("CLOSE");
        btc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcActionPerformed(evt);
            }
        });
        getContentPane().add(btc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 520, -1, -1));

        btu.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btu.setText("UPDATE");
        btu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btuActionPerformed(evt);
            }
        });
        getContentPane().add(btu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 450, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeb.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsActionPerformed
        // TODO add your handling code here:
        String names = name.getText();
        String phones = phone.getText();
        String addrs = addr.getText();
        if (validateFields()) {
            JOptionPane.showConfirmDialog(null, "All fields are required");

        } else {
            try {
                Connection con = DBConnection.getConnection();
                PreparedStatement ps = con.prepareStatement("insert into customer ( name,phone,address) VALUES ( ?, ?, ?)");
                ps.setString(1, names);
                ps.setString(2, phones);
                ps.setString(3, addrs);
                ps.executeUpdate();
                JOptionPane.showConfirmDialog(null, "Customer added successfully");
                setVisible(false);
                new Customer().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
        }
    }//GEN-LAST:event_btsActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) ctable.getModel();
        try {
            Connection con = DBConnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select* from customer");
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("id"), rs.getString("name"), rs.getString("phone"), rs.getString("address"), rs.getString(4)});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        btu.setEnabled(false);
    }//GEN-LAST:event_formComponentShown

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_formMouseClicked

    private void btreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btreActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Customer().setVisible(true);
    }//GEN-LAST:event_btreActionPerformed

    private void btcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btcActionPerformed

    private void btuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btuActionPerformed
        // TODO add your handling code here:
        String names = name.getText();
        String phones = phone.getText();
        String addrs = addr.getText();
        if (validateFields()) {
            JOptionPane.showConfirmDialog(null, "All fields are required");
        } else {
            try {
                Connection con = DBConnection.getConnection();
                PreparedStatement ps = con.prepareStatement("UPDATE customer SET  name = ?,phone=?,address=? where id=?");
                ps.setString(1, names);
                ps.setString(2, phones);
                ps.setString(3, addrs);
                ps.setInt(4, cust_id);
                ps.executeUpdate();
                JOptionPane.showConfirmDialog(null, "Customer updated successfully");
                setVisible(false);
                new Customer().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
        }
    }//GEN-LAST:event_btuActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void ctableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctableMouseClicked
        // TODO add your handling code here:
        int index = ctable.getSelectedRow();
        TableModel model = ctable.getModel();
        String id = model.getValueAt(index, 0).toString();
        cust_id = Integer.parseInt(id);
        String names = model.getValueAt(index, 1).toString();
        name.setText(names);
        String phones = model.getValueAt(index, 2).toString();
        phone.setText(phones);
        String addrs = model.getValueAt(index, 3).toString();
        addr.setText(addrs);
        bts.setEnabled(false);
        btu.setEnabled(true);

    }//GEN-LAST:event_ctableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addr;
    private javax.swing.JButton btc;
    private javax.swing.JButton btre;
    private javax.swing.JButton bts;
    private javax.swing.JButton btu;
    private javax.swing.JTable ctable;
    private javax.swing.JTextField custid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel txtaddr;
    private javax.swing.JLabel txtid;
    private javax.swing.JLabel txtname;
    private javax.swing.JLabel txtphone;
    // End of variables declaration//GEN-END:variables
}
